# Generated by Django 5.0.4 on 2024-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=200)),
                ("correo", models.EmailField(max_length=254)),
                ("ci", models.CharField(blank=True, max_length=12)),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
    ]
