# Generated by Django 5.0.4 on 2025-02-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_precio_producto_precio_bolivares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_en_stock',
            field=models.IntegerField(default=0),
        ),
    ]
