# Generated by Django 5.0.4 on 2025-02-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_cantidad_en_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_bolivares',
            field=models.FloatField(default=0),
        ),
    ]
