# Generated by Django 5.0.4 on 2025-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_alter_item_numero_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_bolivares",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_dolares",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
