# Generated by Django 5.0.4 on 2025-02-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas_y_reportes', '0003_remove_detallefactura_precio_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='nombre',
        ),
    ]
