# Generated by Django 5.0.4 on 2025-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas_y_reportes", "0005_alter_factura_metodo_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallefactura",
            name="seriales",
            field=models.JSONField(default=list),
        ),
    ]
