# Generated by Django 5.0.4 on 2025-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas_y_reportes', '0007_remove_detallefactura_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
